services:

  mysql:
    image: mysql:8.4
    container_name: mysql-turnos
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema-turnos

  backend:
    build: .
    container_name: backend-turnos

    ports:
      - "8080:8080"

    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend-turnos

    ports:
      - "3000:3000"

    depends_on:
      - backend